project:
  type: website
  output-dir: docs
  
website:
  title: "Privacy and Public Policy Conference"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - travel.qmd
      - about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

