---
title: "Conference Schedule"
---

Tentative schedule, subject to change.

+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Day 1             | Friday September 13, 2024                                                                                                                                                                                                |
+===================+:=========================================================================================================================================================================================================================+
| 8:45am - 9:00am   | Introduction                                                                                                                                                                                                             |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9:00am - 10:00am  | **Invited panel**                                                                                                                                                                                                        |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:00am - 10:15am | Coffee and tea break                                                                                                                                                                                                     |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:15am - 12:00pm | **Session 1: Government PETs Applications**                                                                                                                                                                              |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S1-01: Lisa B. Mirel, Cordell Golden, Rob Zybrick, Rui Wang, Chrystine Tadler, and Christine Cox** - Linking Data in a Shared Service Environment                                                                      |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S1-02: Silke Taylor, Josh Miller, Erika Tyagi, Deena Tamaroff, Clayton Seraphin, Graham MacDonald, Claire McKay Bowen, and Aaron R. Williams** - Building an Automated Validation Server Prototype                     |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S1-03: Cordell Golden** - National Center for Health Statistics Data Linkage Program: Generating Synthetic Data to Support Tiered Access                                                                               |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S1-04: Shlomi Hod and Ran Canetti** - Designing the Pilot Release of Israel’s National Registry of Live Births: Reconciling Privacy with Accuracy and Usability                                                        |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:00pm - 1:30pm  | Lunch                                                                                                                                                                                                                    |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1:30pm - 3:15pm   | **Session 2: DP Methods and Applications**                                                                                                                                                                               |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S2-01: Rob Chew, Terrance D. Savitsky, and Matthew R. Williams** - Privacy Preserving Autocoders                                                                                                                       |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S2-02: Ogonnaya Romanus, Younes Boulaguiem, Roberto Molinari, and Stephane Guerrier** - Simulation-Based Differentially Private Inference for Proportions                                                              |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S2-03: Liudas Panavas, Hari Bhimaraju, Wynee Pintado, Rebecca N. Wright, and Rachel Cummings** - A Visualization Tool To Help Technical Practitioners of Differential Privacy                                          |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S2-04: Priyanka Nanayakkara, Jayshree Sarathy, Mary Anne Smart, Rachel Cummings, Gabriel Kaptchuk, and Elissa M. Redmiles** - Eliciting End Users' Privacy-Accuracy Preferences for Differentially Private Deployments |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3:15pm - 3:30pm   | Coffee and tea break                                                                                                                                                                                                     |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3:30pm - 5:00pm   | **Working roundtables**                                                                                                                                                                                                  |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5:00pm - 7:00pm   | **Poster session**                                                                                                                                                                                                       |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-01: Lu Chen, Luca Sartore, Michael Jacobsen, Kado Yeo, and Valbona Bejleri** - Bayesian data synthesis for data with weights                                                                                    |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-02: Christian Cianfarani and Aloni Cohen** - Differential Privacy Does Not Prevent Lawful Redistricting                                                                                                         |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-03: Gary Howarth and Christine Task** - Benchmarking privacy-preserving synthetic data with the collaborative research cycle project                                                                            |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-04: Michael Jacobsen, Kado Yeo, Luca Sartore, and Chen Lu** - Synthetic Microdata Methods For Confidential Agricultural Data                                                                                    |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-05: JN Matthews** **and** **Aloni Cohen** - Whose 2010 Census responses can be reconstructed with certainty?                                                                                                    |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-06: Vasundhara Kaul and Tamalika Mukherjee** - Equitable Differential Privacy                                                                                                                                   |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-07: Casey Meehan, David Pujol, Damien Desfontaines, and Ashwin Machanavajjhala** - Is My Synthetic Data Actually Private? A Framework For Empirical Privacy Metrics                                             |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-08: Sarah Radway, Katherine Quintanilla, Cordelia Ludden, and Daniel Votipka** - An Investigation of US Universities' Implementation of FERPA Student Directory Policies                                        |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-09: Samuel Dooley, Dana Turjeman, John P Dickerson, and** **Elissa M. Redmiles** - The Impact of Statements about Privacy & Data Collection On Privacy-Sensitive App Adoption                                   |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-10: Jingchen Hu, Matthew R. Williams, and Terrance D. Savitsky** - Mechanisms for Global Differential Privacy under Bayesian Data Synthesis                                                                     |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-11: Jeremy Seeman** - Privacy’s odd couple: privacy law and privacy engineering on inference and information recovery Legitimacy strategies and privacy-enhancing technology policy                             |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-12: Amy O’Hara and Stephanie Straus** - An Exploration of Secure Enclaves to Increase State Agency Data Access                                                                                                  |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-13: Ruizhe Wang, Aarushi Dubey, Roberta De Viti, Deepak Garg, and Elissa M. Redmiles** - The Role of Privacy Guarantees in Voluntary Donation of Private Data for Altruistic Goals                              |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-14: Hang J. Kim, Terrance Savitsky, Matt Williams, and Monika Hu** - Synthetic population generation for nested data using differentially private posteriors                                                    |
|                   |                                                                                                                                                                                                                          |
|                   | -   **P1-15: Alexandra Wood and Marco Gaboardi** - The Role of Synthetic Data in Privacy Governance                                                                                                                      |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Day 2             | Saturday September 14, 2024                                                                                                                                                                                     |
+===================+:================================================================================================================================================================================================================+
| 9:00am - 10:45am  | **Session 3: Synthetic Data Methods and Applications**                                                                                                                                                          |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S3-01: Luca Sartore, Lu Chen, Michael Jacobsen, Kado Yeo, and Valbona Bejleri** - High-Dimensional Synthetic Data Via Nearest Neighbors                                                                       |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S3-02: Medha Uppala, Minsun Riddles, Tom Krenzke, Natalie Shlomo, Angela Chen, Robyn Ferg, and Lin Li** - Research and Applications of Select Synthetic Data Approaches at Westat                             |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S3-03: Ayat Almomani, Hang J. Kim, Won Chang, and Youngdeok Hwang** - Automatic Variance Adjusted Bayesian Inference with Pseudo Likelihood under Unequal Probability Sampling: Imputation and Data Synthesis |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S3-04: Cameron Bale and Harrison Quick** - Optimized Sequential Synthesis with an Application to Legal Anonymization                                                                                          |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:45am - 11:00am | Coffee and tea break                                                                                                                                                                                            |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:00am - 12:45pm | **Session 4: Privacy Perspectives**                                                                                                                                                                             |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S4-01: Elan Segarra** - Estimating Preferences Over Data to Inform Statistical Disclosure Methods                                                                                                             |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S4-02: Severin Engelmann and Helen Nissenbaum** - Countering Privacy Nihilism                                                                                                                                 |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S4-03: James Bailie, Roubin Gong, and Xiao-Li Meng** - Can Swapping be Differentially Private? A Refreshment Stirred, not Shaken                                                                              |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   | **S4-04: Rachel Cummings, Talia Gillis, and** **Tamalika Mukherjee** - The Hidden Costs of Privacy Choice for Marginalized Groups                                                                               |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:45pm - 2:00pm  | Lunch and wrap-up                                                                                                                                                                                               |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
