---
title: "Travel Support and Poster Awards"
---

# Travel Support

Thanks to the generous support from the Alfred P. Sloan Foundation (G-2022-19513), we are happy to support up to **three** student travel awards. Below you will find detailed information.

## Information

The Privacy and Public Policy Conference will award up to three travel awards of \$1500 to students in order to cover the costs of attending the conference. Prioritization will be given to students presenting a paper or poster.

Priority is also given to students who have no other source of funds to finance travel to the conference. The application requires a short note from the student's main faculty advisor substantiating that the student does not have access to other funds to support conference engagement. Applications will be evaluated based on the student's Personal Statement, which must include the applicant's current research interest(s) and professional development goals, as well as how the conference would help the student achieve those goals.

## Application

All applicants should submit their application materials to privacy dot and dot public dot policy dot conference at proton dot me (privacy.and.public.policy.conference@proton.me) **by May 1, 2024** to receive full consideration. Each application should include the following:

1.  **CV** (including the applicant's name, address, email, current institution, program of study, and number of years in the current program)

2.  **A Personal Statement** (maximum 1 page) that includes:

    -   The applicants research interests
    -   Professional development goals
    -   How the conference will help the applicant with these research interests and goals

3.  **A letter of support from a faculty advisor**, which confirms that the applicant is a student in good standing in their program and explains that there is no other funding available to cover the expenses from attending the conference.


# Poster Awards

We are thrilled to announce that there will be **two** poster awards among posters presented during the poster session.  

Check out the [schedule](schedule.qmd) for information about the poster session.

Consider being a poster session judge when [register](registration.qmd) for the conference.