---
title: "Travel Guide"
---

# Travel Guide for Georgetown University Capitol Campus

125 E Street NW, Washington, DC 20001

## Transportation

### Metrorail

The Capitol Campus is near Judiciary Square (Red Line), Union Station (Red Line) and Gallery Place (Green/Yellow Line) Metro stops. 

- From Judiciary Square (±6 minute walk): 

    1. Exit the station on 4th St NW 
    2. From the escalators, turn around and head toward E St NW
    3. Turn right onto E St NW
    4. Enter the building on your left
    
- From Union Station (±10 minute walk):

    1. Exit the station on Union Station Dr NE
    2. Turn right from the station toward E St NW
    3. Continue on E St NW
    4. Enter the building on your right
    
- From Gallery Place (±12 minute walk):

    1. Exit the station on 7th and F St NW
    2. Turn left from the station towards F St NW
    3. Walk straight to continue onto F St NW
    4. Turn right onto 6th St NW
    5. Turn left onto E St NW
    6. Enter the building on your left
    
### Rideshare

Rideshare options are plentiful throughout the area. Rate will vary. To arrive, put your destination address as 125 E St NW.


### Driving + Parking 

Parking is very limited. For outside visitors seeking parking near campus, we recommend the following options:

- 99 H Street NW
- 601 New Jersey Ave NW (across from McDonough Hall)
- 200 Massachusetts Ave NW (Capitol Crossing) across from Law Library
- 500 New Jersey Ave NW

There is some metered parking available around the Capitol Campus.  Use SpotHero to secure your parking ahead of time.


## Hotels

[Hyatt Regency Washington On Capitol Hill](https://www.hyatt.com/en-US/hotel/washington-dc/hyatt-regency-washington-on-capitol-hill/wasrw?src=corp_lclb_gmb_seo_wasrw)

400 New Jersey Ave NW, Washington, DC 20001 


[Hilton Washington DC Capitol Hill](https://www.hilton.com/en/hotels/dcadchh-hilton-washington-dc-capitol-hill/?SEO_id=GMB-AMER-HH-DCADCHH&y_source=1_MjAwNzc5NjEtNzE1LWxvY2F0aW9uLndlYnNpdGU%3D)

525 New Jersey Ave NW, Washington, DC 20001


[YOTEL Washington DC](https://www.yotel.com/en/hotels/yotel-washington-dc?utm_source=Google&utm_medium=Yext_YOWDC)

415 New Jersey Ave NW, Washington, DC 20001


[Phoenix Park](https://www.phoenixparkhotel.com/)

520 North Capitol St NE, Washington, DC 20001


[Royal Sonesta](https://www.sonesta.com/royal-sonesta/dc/washington/royal-sonesta-washington-dc-capitol-hill)

20 Massachusetts Ave NW, Washington, DC 20001 


[Kimpton George Hotel](https://www.hotelgeorge.com/?&cm_mmc=WEB-_-KI-_-AMER-_-EN-_-EV-_-Google%20Business%20Profile-_-DD-_-george)

15 E St NW, Washington, DC 20001


## Dining

- Seated Dining

    - The Dubliner 
    - Hamilton's Bar & Grill
    - L’Ardente 
    - Love, Makoto
    - Jaleo
    - Mi Vida
    
    
- Quick and Casual
  
    - 125 E St cafe (2nd floor)
    - SunDeVich 
    - Tatte Bakery 
    - Cafe Alice 
    - [Union Station Dining](https://www.unionstationdc.com/dining/)
    - Z Burger
    
- Coffee/Cafes

    - Ministry Coffee
    - Tatte Bakery
    - Blue Bottle Coffee
    - Teaism



